### ISSUE TITLE
Hand tracking (CPU) example not working on Windows 10

### ISSUE THREAD

**Issue by luabras** [google/mediapipe#1225]
When running the site hand tracking (cpu) example, the following error appears:

E20201023 15:16:17.180711 19164 demo_run_graph_main.cc:146] Failed to run the graph: ; Can't find file:

I already checked the folders and the pbtxt files are in the correct locations, the error stops at "Can't find file:" and does not specify which file is missing, what should I do? I managed to run the Hello World example, but not this one.

**Comment by BalajiB197** [comment]
the same issue even I am facing, any workaround you found ??

**Comment by Lr-2002** [comment]
Hey ,guys ,is the problem ever fixed?

**Comment by Lr-2002** [comment]
Well ,this problem has ever been fixed in [#1372](https://github.com/google/mediapipe/issues/1372)

**Comment by sgowroji** [comment]
Hi @luabras, Could you please confirm the above issue still exists

**Comment by sgowroji** [comment]
Hi @luabras, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1225#issuecomment-851846213). Thanks

**Comment by sgowroji** [comment]
We are closing this issue now due to lack of activity. Please feel free to reopen if you have any relevant update on the above. Thanks.
