### ISSUE TITLE
[javascript] errors occur when pose.send() is not the first line in animation function

### ISSUE THREAD

**Issue by dewball345** [google/mediapipe#1412]
Hello there,
I wanted to try and use the new Mediapipe pose as an alternative to posenet, but I encountered several errors when using it in my webpage, which can be found at https://glitch.com/edit/#!/prong-periwinkle-friend.

You may not receive these errors, but I received them all at some point in time:
`
Uncaught TypeError: Cannot read property 'https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_packed_assets.data' of undefined
    at XMLHttpRequest.xhr.onprogress (VM140 pose_solution_packed_assets_loader.js:48)
`
and
`
Uncaught (in promise) RuntimeError: abort(Assertion failed: undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:67548)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:67724)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:41039)
    at assert (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:28443)
    at Object.addRunDependency (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:39866)
    at DataRequest.open (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_packed_assets_loader.js:117:37)
    at runWithFS (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_packed_assets_loader.js:143:84)
    at callRuntimeCallbacks (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:66525)
    at preRun (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:38114)
    at run (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:380126)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:41070)
    at assert (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:28443)
    at Object.addRunDependency (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:39866)
    at DataRequest.open (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_packed_assets_loader.js:117:37)
    at runWithFS (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_packed_assets_loader.js:143:84)
    at callRuntimeCallbacks (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:66525)
    at preRun (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:38114)
    at run (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:380126)
    at runCaller (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:379984)
    at removeRunDependency (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:40825)
`
as well as
`
VM345 pose_solution_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:67548)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:67724)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:41039)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:21812)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:21636
    at da.h (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:28:51)
    at Q (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:10:294)
    at ka.next (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:11:89)
    at k (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:22:318)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:41070)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:21812)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:21636
    at da.h (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:28:51)
    at Q (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:10:294)
    at ka.next (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:11:89)
    at k (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose.js:22:318)
`
and finally
`
WebGL: INVALID_OPERATION: texParameter: no texture bound to target
`
and also one about Memory out of bounds, but I can't seem to get that error running again.

Sometimes, Mediapipe Pose would work for a few seconds and then show the last and second-to-last errors, and sometimes it would just not work at all. Somehow, it would work in a different project, but it would suddenly not work when I copy-and-pasted the exact same bits of code into this one. I really don't understand what I'm missing here.

"working" example(it doesn't work on glitch but it somehow works on my local device): https://glitch.com/edit/#!/surf-super-aphid

**Comment by dewball345** [comment]
noticed something interesting - the pose.send() must be the first line executed in the animation loop, or else these kinds of errors will occur.
ex.

this won't cause an error:

function predict(){
     pose.send({image:video});
     window.requestAnimationFrame(predict);
}


nor will this:

function sub(){
     pose.send({image:video});
}
function predict(){
     sub();
     window.requestAnimationFrame(predict);
}

but this will cause an error:

function predict(){
    console.log("hi");
    pose.send({image:video});
    window.requestAnimationFrame(predict);
}

ps. sorry about the bad formatting, i couldn't use the code block because it made things look even worse(removed newline)

**Comment by dewball345** [comment]
> noticed something interesting - the pose.send() must be the first line executed in the animation loop, or else these kinds of errors will occur.
> ex.
> 
> this won't cause an error:
> 
> function predict(){
> pose.send({image:video});
> window.requestAnimationFrame(predict);
> }
> 
> nor will this:
> 
> function sub(){
> pose.send({image:video});
> }
> function predict(){
> sub();
> window.requestAnimationFrame(predict);
> }
> 
> but this will cause an error:
> 
> function predict(){
> console.log("hi");
> pose.send({image:video});
> window.requestAnimationFrame(predict);
> }
> 
> ps. sorry about the bad formatting, i couldn't use the code block because it made things look even worse(removed newline)

why would this occur?

**Comment by mzwtjp** [comment]
JFYI, in my case with similar error log, I needed to wait for video element loadeddata event so that I can be sure the video element is loaded with the image data and prediction no longer crashed.

**Comment by AmeanAsad** [comment]
@mhays-google  Have you had a chance to look at this?

**Comment by sgowroji** [comment]
Hi @dewball345, Could you please check the above error with the latest release and let us know if you still see it. Thanks!

**Comment by mhays-google** [comment]
I addressed this issue for our TF-js and I think it's fixed.

**Comment by positlabs** [comment]
I'm still having this issue. It could be a problem with my initialization flow, but I fixed it by preventing holistic.send from being called before the previously requested results come back. 

```
let gotResults = true
um.addEventListener('frameupdate', async () => {
  if(gotResults) {
    gotResults = false
    await holistic.send({ image: videoElement })
    gotResults = true
  }
})
```
