### ISSUE TITLE
Definitions for 468 landmark points of a face

### ISSUE THREAD

**Issue by mzwtjp** [google/mediapipe#1615]
I am looking into javascript versions of face_mesh and holistic solution APIs.
As for face landmarks, the doc says:

>MediaPipe Face Mesh is a face geometry solution that estimates 468 3D face landmarks in real-time even on mobile devices. 

Correspondence between 468 3D points and actual points on the face is a bit unclear to me.
e.g. Which is the nose top, chin or tops of cheekbones?

I can only guess from faceLandmarks array (by checking its indices and how they are plotted on app screen canvas) or FACEMESH_LIPS, FACEMESH_LEFT_EYE, etc. objects (the latter seems to be telling me the polygons for each face parts), but this is just a guess.

It is a great help if I can find a diagram of a head (or skull) together with 468 landmark indices.

I imagine the meanings of indices may change when the model is enhanced in the future?  But for a version of api, doc defining the meanings of landmark indices (or symbols for key landmarks that I can access in my code) is important.
At least meanings to the key points in FACEMESH_xxxx symbols (e.g. outer/inner corners of eyes) for convenience.

**Comment by mzwtjp** [comment]
I have found below could be the doc about landmark indices.  It helps, but any meanings to them (e.g. xxx are left/right cheekbone top, xxx is the top (peak) of he nose), etc.?

https://github.com/tensorflow/tfjs-models/tree/master/facemesh

**Comment by ianni67** [comment]
This might help you: I found it matches the mediapipe landmarks. [https://webgazer.cs.brown.edu/node_modules/@tensorflow-models/facemesh/mesh_map.jpg](url)

**Comment by aarushi-mittal** [comment]
Hello , thank you for opening a thread on this.
Is https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg also the index order in the landmark array that gets generated for plotting ?

I want to distinguish between the left side and right side of a face while turning ?
However, the coordinates derived from the facemesh for left and right corner of the eyes seem to be a hardcoded set.

Even when my right side of face occupies the screen, the left eye corner coordinates are captured.

Any help would be highly appreciated.

Thank you,
Aarushi

**Comment by sgowroji** [comment]
Hi @mzwtjp, Could you please confirm your above query is resolved or answered. Thanks!

**Comment by mzwtjp** [comment]
Well, I still do not feel they are clearly defined (in public description of APIs), but it is OK for now - I understand that it is simply "face mesh model just plotted this way."

**Comment by salsabeel123** [comment]
Hello, I need a list of 468 face landmarks names.

**Comment by arashtavakoli** [comment]
I am also looking for the names of each landmark.

**Comment by vinothinips** [comment]
Hello, I am also looking for the list of 468 landmark names! Please share if you have

**Comment by arashtavakoli** [comment]
Kinda interesting that I cannot find this anywhere on the documentation. Starting to think that I misunderstood the purpose of this. Because honestly without knowing the names of landmarks it sounds really hard to use them for some specific applications.

**Comment by salsabeel123** [comment]
> I have found a link, but it does not have all landmarks' names.
below is the link
https://github.com/tensorflow/tfjs-models/commit/838611c02f51159afdd77469ce67f0e26b7bbb23

**Comment by willstott101** [comment]
Perma link to an image in this repo showing the points: https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

**Comment by jhan15** [comment]
> Perma link to an image in this repo showing the points: https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

This is really useful! I find that there are 478 landmarks now. I tried hard to examine the image, but I failed to find the indices after 468. I'm assuming that more landmarks were added to refine the mesh, but the previous index sequence remained unchanged. Can anyone confirm my assumption? Thank you!

**Comment by ashok-arjun** [comment]
> 

More precisely the landmarks are in the file at this permalink:

https://github.com/tensorflow/tfjs-models/blob/838611c02f51159afdd77469ce67f0e26b7bbb23/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts

**Comment by ashok-arjun** [comment]
More precisely the landmarks are in the file at this permalink:

https://github.com/tensorflow/tfjs-models/blob/838611c02f51159afdd77469ce67f0e26b7bbb23/face-landmarks-detection/src/mediapipe-facemesh/keypoints.ts

**Comment by rcsmit** [comment]
I anotated an image of Gal Gadot with the ID's of the landmarks 

https://github.com/rcsmit/python_scripts_rcsmit/blob/master/extras/Gal_Gadot_by_Gage_Skidmore_4_5000x5921_annotated_black_letters.jpg

https://github.com/rcsmit/python_scripts_rcsmit/blob/master/extras/Gal_Gadot_by_Gage_Skidmore_4_5000x5921_annotated_white_letters.jpg

**Comment by robin2046** [comment]
> Perma link to an image in this repo showing the points: https://github.com/google/mediapipe/blob/a908d668c730da128dfa8d9f6bd25d519d006692/mediapipe/modules/face_geometry/data/canonical_face_model_uv_visualization.png

Thanks for this information.
However, I am confused why iris tracking impl select the following landmarks to crop the ROI of left eye?

# Gets two landmarks which define left eye boundary.
node {
  calculator: "SplitNormalizedLandmarkListCalculator"
  input_stream: "face_landmarks"
  output_stream: "left_eye_boundary_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.SplitVectorCalculatorOptions] {
      ranges: { begin: 33 end: 34 }
      ranges: { begin: 133 end: 134 }
      combine_outputs: true
    }
  }
}

I can see 33 and 133 are the left/right corner of the eye, but what about 34 and 134?
Why these two landmarks are used?
Any inspiration is really appreciated!
Thanks a lot.

**Comment by ianni67** [comment]
There's quite a lot of confusion about this topic.

Mediapipe has its separate Eye irises detection model 
https://google.github.io/mediapipe/solutions/iris.html so when I 
experimented with it I used the Iris model for iris tracking (though I 
used the face model to detect where the eyes were). Moreover, in 2020 a 
second, more complete module has been release, 
https://blog.tensorflow.org/2020/11/iris-landmark-tracking-in-browser-with-MediaPipe-and-TensorFlowJS.html 
that I never used.

It should overcome several issues with the previous module, but I did 
not check it thoroughly. This secondo module probably adopts an 
integrated face and iris module, with completely different landmarks 
that also include iris landmarks. But be careful, because when I tried 
it, the facegeometry module was still not compatible with this enhanced 
model.


Il 23/11/22 17:11, DavidRobin ha scritto:

**Comment by ZYCourage** [comment]
I also want to know names of each landmarks. I want to detect if people wink their eyes by mediapipe. If I know these names, I could solve this problem simply using an if sentence.

**Comment by Chailex** [comment]
Is there any data on which landmark is connected to which landmarks? Is there a list with such data available? I have searched a lot but didn't find anything related to it. Can anyone help with it.

**Comment by neo** [comment]
I had been using the Gal Gadot reference from above, but today I found this one with iris too from: https://developers.google.com/mediapipe/solutions/vision/face_landmarker/index#models

![](https://storage.googleapis.com/mediapipe-assets/documentation/mediapipe_face_landmark_fullsize.png)
