### ISSUE TITLE
FaceDetection - Missing field:  "valueString" 

### ISSUE THREAD

**Issue by iCrashOne** [google/mediapipe#2346]
I created a small project with React to test out face_detection and selfie segmentation. However I'm getting this error when calling the initialize() / send() methods

Chrome version: Version 92.0.4515.107 (Official Build) (64-bit)
OS: Debian GNU/Linux 10 (buster)

![2021-07-27_16-54](https://user-images.githubusercontent.com/88058651/127232580-4c25fa25-a494-4d43-a79e-fd828ec22d36.png)

Dependencies
```json
"dependencies": {
    "@mediapipe/control_utils": "^0.6.1626288889",
    "@mediapipe/drawing_utils": "^0.3.1620248257",
    "@mediapipe/face_detection": "^0.4.1624566703",
    "@mediapipe/selfie_segmentation": "^0.1.1622680987",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
```
React Component
```jsx
import React, { useEffect, useRef, useCallback } from "react";
import { FaceDetection } from "@mediapipe/face_detection";
import { drawRectangle, drawLandmarks } from "@mediapipe/drawing_utils";
import { SelfieSegmentation } from "@mediapipe/selfie_segmentation";

const App = () => {

  const videoRef = useRef(null);
  const canvasRef = useRef(null);

  const onSsResults = (results) => {
    // do stuff with results
  };

  const onResults = (results) => {
    // do stuff with results
  };

  const start = async () => {
    const faceDetection = new FaceDetection({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4/${file}`;
      },
    });
    const selfieSegmentation = new SelfieSegmentation({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1/${file}`;
      },
    });
    selfieSegmentation.setOptions({
      selfieMode: true,
      modelSelection: 1,
      effect: "background",
    });
    selfieSegmentation.onResults(onSsResults);

    faceDetection.setOptions( {
      selfieMode: true,
      model: "short",
      minDetectionConfidence: 0.5,
    });
    faceDetection.onResults(onResults);
    await selfieSegmentation.initialize();
    await faceDetection.initialize();
    setInterval(async () => {
      await faceDetection.send({
        image: videoRef.current,
      });
      // await selfieSegmentation.send({
      //   image: videoRef.current,
      // });
    }, 60);
  };

  const setVideo = async () => {
    const stream = await navigator.mediaDevices.getUserMedia({
      video: true,
    });

    videoRef.current.srcObject = stream;

    videoRef.current.play();
    start();
  };
  useEffect(() => {
    setVideo();
  }, []);
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
      }}
    >
      <video style={{ transform: "rotateY(180deg)" }} ref={videoRef}></video>
      <canvas
        style={{ width: "640px", height: "480px" }}
        ref={canvasRef}
      ></canvas>
    </div>
  );
};

export default App;
```

Note: On MacOs this code works fine

**Comment by wjps** [comment]
We also started seeing this yesterday across a variety of OSs (Linux, MacOS & Windows). 

It looks like a new npm version and set of model files was released yesterday and there's an incompatibility between them (in both directions).

@iCrashOne updating to the current version of the npm fixed the issue for us. Alternatively specify the exact version of the model files for the older npm release (0.4.1624566703) when loading the files.

`https://cdn.jsdelivr.net/npm/@mediapipe/face_detection@0.4.1624566703/${file}`

**Comment by dydx-git** [comment]
I'm seeing this on blazepose using mediapipe-gpu as backend. Even the official demo is now crashing: https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=blazepose

**Comment by mhays-google** [comment]
I will check immediately.

**Comment by mhays-google** [comment]
This is a caching issue on the part of jsdelivr.  I have now written a
script that will allow me to purge the cache entries for people who use
only the default/major/minor designator, which, let's face it, is all of us.

I've already run the purge, and the demo seems to work.  I'm going to go
through and purge the cache for all of our other libraries today, but I
think this should be fixed.

Thank you for your patience, and sorry for the inconvenience.

**Comment by wjps** [comment]
Will that fix the problem? I think it's more often caused when you have a
(slightly) outdated npm package and are getting the latest model files from
the CDN.

I think either the model files need to be compatible with previous minor
releases or the files need to be referenced using the exact version string.
If the latter then it would be nice if it were possible to get the full
version string out of the package somehow.

**Comment by dydx-git** [comment]
agreed @wjps this issue was fixed in https://github.com/tensorflow/tfjs-models/pull/766

**Comment by positlabs** [comment]
I'm still seeing this issue in the latest version. 

<img width="986" alt="Screen Shot 2022-02-25 at 10 25 39 AM" src="https://user-images.githubusercontent.com/1918844/155741714-660a8b36-9342-4555-ad72-f0edb8d6a048.png">
