### ISSUE TITLE
install mediapipe 0.8.10 on python macos (apple silicon - M1)

### ISSUE THREAD

**Issue by SajjadAemmi** [google/mediapipe#3415]
i am try to build mediapipe on my macos python (apple silicon - M1)
tested python versions: 3.8 - 3.9 - 3.10 
i run these commands:
```
git clone https://github.com/google/mediapipe.git
cd mediapipe
python3 setup.py install
```

but i face this error:
```
[ 98%] Linking CXX static library ../../lib/libopencv_calib3d.a
[ 98%] Built target opencv_calib3d
Scanning dependencies of target opencv_highgui
[ 98%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/window.cpp.o
[ 98%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/roiSelector.cpp.o
[ 98%] Building CXX object modules/highgui/CMakeFiles/opencv_highgui.dir/src/window_cocoa.mm.o
[ 98%] Linking CXX static library ../../lib/libopencv_highgui.a
[ 98%] Built target opencv_highgui
Scanning dependencies of target opencv_annotation
[ 98%] Building CXX object apps/annotation/CMakeFiles/opencv_annotation.dir/opencv_annotation.cpp.o
[ 98%] Linking CXX executable ../../bin/opencv_annotation
Undefined symbols for architecture arm64:
  "_jpeg_default_qtables", referenced from:
      cv::JpegEncoder::write(cv::Mat const&, std::__1::vector<int, std::__1::allocator<int> > const&) in libopencv_imgcodecs.a(grfmt_jpeg.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
/private/var/tmp/_bazel_sajjadaemmi/f786f97fb76e701d8265b2cf8b045437/sandbox/darwin-sandbox/139/execroot/mediapipe/external/local_config_cc/cc_wrapper.sh: line 69: 16324 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
make[2]: *** [bin/opencv_annotation] Error 134
make[1]: *** [apps/annotation/CMakeFiles/opencv_annotation.dir/all] Error 2
make: *** [all] Error 2
_____ END BUILD LOGS _____
rules_foreign_cc: Build wrapper script location: bazel-out/darwin_arm64-opt/bin/third_party/opencv_cmake_scripts/CMake_wrapper_script.sh
rules_foreign_cc: Build script location: bazel-out/darwin_arm64-opt/bin/third_party/opencv_cmake_scripts/CMake_script.sh
rules_foreign_cc: Build log location: bazel-out/darwin_arm64-opt/bin/third_party/opencv_cmake_logs/CMake.log

Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 682.946s, Critical Path: 524.41s
INFO: 2014 processes: 239 internal, 1775 darwin-sandbox.
FAILED: Build did NOT complete successfully

```

**Comment by saiedg** [comment]
@SajjadAemmi  Any update on this?

**Comment by SajjadAemmi** [comment]
@saiedg Did you test version 0.8.11?

**Comment by kuaashish** [comment]
Hi @SajjadAemmi,
This issue has been fixed in the latest release of the version `0.8.11` and was able to build as well import the mediapipe in python interpreter as screenshot attached. Please have look here and feel free to close this issue if this is no longer a issue from your end. 
<img width="1728" alt="3415" src="https://user-images.githubusercontent.com/98159216/207250107-c66f44b3-478a-4588-8681-711c2882abad.png">

**Comment by SajjadAemmi** [comment]
@kuaashish Do you have M1? or intel?
I still have the error.

**Comment by kuaashish** [comment]
@SajjadAemmi,
This has been tested on the chip Apple M1 Pro, macOS Ventura 13.0.1. If still an issue from your end feel free to re-open the issue.

**Comment by SajjadAemmi** [comment]
@kuaashish My error is about opencv. how did you install opencv?

**Comment by kuaashish** [comment]
@SajjadAemmi,
I have followed the documentation to build mediapipe as mentioned [here](https://google.github.io/mediapipe/getting_started/install.html#installing-on-macos) and followed the steps 4 to install Install OpenCV. Could you try with latest version 0.8.11 and re-build again in the device.
