### ISSUE TITLE
Object Detection Tensorflow does not execute on Linux

### ISSUE THREAD

**Issue by PZerua** [google/mediapipe#3530]
**System information**
- OS Platform and Distribution: Linux Kubuntu 20.04
- Compiler version: gcc 9.4.0
- Programming Language and version: C++
- MediaPipe version: v0.8.10.2
- Bazel version: 5.2.0
- OpenCV version: 4.2

**Describe the problem**:
On Linux I can compile Object Detection with the Tensorflow model (following steps in [docs](https://google.github.io/mediapipe/solutions/object_detection.html#desktop)), but when executing it shows a lot of Tensorflow related errors and does not generate any output. No problems when compiling and executing the Object Dectection with TFLite model.

**Provide the exact sequence of commands / steps that you executed before running into the problem:**

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true --linkopt=-s \
  mediapipe/examples/desktop/object_detection:object_detection_tensorflow

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/object_detection/object_detection_tensorflow \
  --calculator_graph_config_file=mediapipe/graphs/object_detection/object_detection_desktop_tensorflow_graph.pbtxt \
  --input_side_packets=input_video_path=video.mp4,output_video_path=video_out.mp4
```

**Complete Logs:**
[log.txt](https://github.com/google/mediapipe/files/9143241/log.txt)

**Comment by kuaashish** [comment]
Hi @PZerua, Could you please confirm that you are still looking for resolution or the issue has been resolved. Thank you!

**Comment by PZerua** [comment]
It still don't execute. Same errors as seen in the log attached in OP.

**Comment by kuaashish** [comment]
Hello @PZerua,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
