### ISSUE TITLE
Missing .tflite  files from every solution in  repository

### ISSUE THREAD

**Issue by prakhar-s-srivastava** [google/mediapipe#3766]
Every Media pipe solution .tflite is missing this is build issue I believe.

**Comment by kuaashish** [comment]
Hi @prakhar-s-srivastava, 
Could you confirm that issue has been resolved as per the above [comment](https://github.com/google/mediapipe/issues/3766#issuecomment-1275886559). Thank you!

**Comment by vinayak19th** [comment]
The tflite files are still missing from the modules folder, had to download them from an old tage

**Comment by kuaashish** [comment]
Hi @vinayak19th,
Could you raise a new issue with complete error logs and followed steps to reproduce the issue from our end. Thank you!
