### ISSUE TITLE
android,0.9.3,build error

### ISSUE THREAD

**Issue by fengyun21** [google/mediapipe#4324]
### OS Platform and Distribution

macos13.3,android,0.9.3,xcode14.2

### Compiler version

xcode-select version 2397

### Programming Language and version

python3.11,openjdk version "20"

### Installed using virtualenv? pip? Conda?(if python)

no

### MediaPipe version

0.9.3

### Bazel version

Bazelisk version: development,Build label: 6.1.1

### XCode and Tulsi versions (if iOS)

xcode14.2

### Android SDK and NDK versions (if android)

sdk30.0.3,ndk21.1.6352462

### Android AAR (if android)

Yes

### OpenCV version (if running on desktop)

maybe opencv3

### Describe the problem

```shell
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
```

### Complete Logs

```shell
INFO: Found 1 target...
ERROR: /Users/apple/mediapipe/mediapipe/mediapipe/modules/palm_detection/BUILD:33:26: Linking mediapipe/modules/palm_detection/palm_detection_model_loader_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/palm_detection:palm_detection_model_loader_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/palm_detection/palm_detection_model_loader_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_apple/85fef98c262989ddaf244e3fdab8e148/execroot/mediapipe/bazel-out/_tmp/actions/stderr-2) 1460423 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
ERROR: /Users/apple/mediapipe/mediapipe/mediapipe/modules/hand_landmark/BUILD:35:26: Linking mediapipe/modules/hand_landmark/hand_landmark_model_loader_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/hand_landmark:hand_landmark_model_loader_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/hand_landmark/hand_landmark_model_loader_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_apple/85fef98c262989ddaf244e3fdab8e148/execroot/mediapipe/bazel-out/_tmp/actions/stderr-3) 1460423 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
ERROR: /Users/apple/mediapipe/mediapipe/mediapipe/modules/palm_detection/BUILD:61:26: Linking mediapipe/modules/palm_detection/palm_detection_gpu_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/modules/palm_detection:palm_detection_gpu_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/palm_detection/palm_detection_gpu_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_apple/85fef98c262989ddaf244e3fdab8e148/execroot/mediapipe/bazel-out/_tmp/actions/stderr-6) 1872147 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.222s, Critical Path: 4.76s
INFO: 10 processes: 10 internal.
FAILED: Build did NOT complete successfully
```

**Comment by fengyun21** [comment]
i try 0.9.2.1 , it compile ok.

**Comment by kuaashish** [comment]
Hello @fengyun21,
Would you please confirm that you are able to run the Hello_World example as noted here in the [guide](https://developers.google.com/mediapipe/framework/getting_started/install)? Thank you

**Comment by fengyun21** [comment]
> 

the Hello_world  example of framework compiled ok.
but the android or ios example compiled failed.

the error msg is:
Linking mediapipe/modules/hand_landmark/hand_landmark_landmarks_to_roi_graph_text_to_binary_graph [for tool] failed

the. detail error msg can see [https://github.com/google/mediapipe/issues/4324](url)

**Comment by fengyun21** [comment]
> Hello @fengyun21, Would you please confirm that you are able to run the Hello_World example as noted here in the [guide](https://developers.google.com/mediapipe/framework/getting_started/install)? Thank you

the Hello_world  example of framework compiled ok.
but the android or ios example compiled failed.

**Comment by Evizero** [comment]
I have the same issue. The linked issue seems quite old. I would have imagined this would affect more people

**Comment by kuaashish** [comment]
Hello @fengyun21,
Apologies for the delayed response. Could you please confirm that still you are looking for resolution or the issue has been solved from your end. Thank you!

**Comment by fengyun21** [comment]
> Hello @fengyun21, Apologies for the delayed response. Could you please confirm that still you are looking for resolution or the issue has been solved from your end. Thank you!

Not resolved yet

Temporarily replaced with mediapipe of 0.9.2.1

**Comment by kuaashish** [comment]
@fengyun21,

We have released newer version mediapipe 0.10.0 as noted here the [release notes](https://github.com/google/mediapipe/releases). Please try out to build the Android example in latest version and let us know if still an issue from other end.

Thank you!

**Comment by PrinceP** [comment]
Same issue in mac, tried with v0.9.3.0 also but not working

**Comment by fengyun21** [comment]
> @fengyun21,
> 
> We have released newer version mediapipe 0.10.0 as noted here the [release notes](https://github.com/google/mediapipe/releases). Please try out to build the Android example in latest version and let us know if still an issue from other end.
> 
> Thank you!

Same issue in mac, tried with v0.10.0 also but not working

**Comment by kuaashish** [comment]
@fengyun21,
Please allow us sometime to share the possible cause of the issue. Thank you

**Comment by fengyun21** [comment]
> @fengyun21, Please allow us sometime to share the possible cause of the issue. Thank you

maybe you can view this post:
[]((https://github.com/google/mediapipe/issues/4324#issuecomment-1558649575)
)
[lyqaiym](https://github.com/lyqaiym) commented [last week](https://github.com/google/mediapipe/issues/4296#issuecomment-1550590163) • 
https://github.com/bazelbuild/bazel
src/main/java/com/google/devtools/build/lib/rules/genrule/GenRuleBaseRule.java
the line 89,new version ExecutionTransitionFactory.create(),old version HostTransition.createFactory().
old is ok.
ExecutionTransitionFactory.java
change coreOptions.isHost = true;
bazel-bin/src/bazel-dev

**Comment by kuaashish** [comment]
@fengyun21,

Could you please reproduce this issue in the latest version 0.10.0 and report back to us if you see the similar failure as described here. We will definitely look into it further. However, We do not have similar machine to reproduce the issue from our end.  Thank you!

**Comment by cancan101** [comment]
I am getting similar errors against current master (`4c4a1d93b28f6f40ffcb11aa11cfbfc26ef0dc68`) trying to run ` bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`:
```
duplicate symbol 'descriptor_table_mediapipe_2fframework_2fformats_2fimage_5fformat_2eproto_getter()' in:
    bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/framework/formats/libimage_format_cc_proto.lo(image_format.pb.o)
    bazel-out/applebin_macos-darwin_x86_64-opt-exec-50AE0418-ST-cfb676c6944e/bin/mediapipe/framework/formats/libimage_format_cc_proto.lo(image_format.pb.o)
...
char_traits<char>, std::__1::allocator<char> >*)' in:
    bazel-out/applebin_macos-darwin_x86_64-opt-exec-50AE0418-ST-cfb676c6944e/bin/external/com_google_protobuf/libprotobuf_lite.lo(wire_format_lite.o)
    bazel-out/darwin-opt-exec-50AE0418/bin/external/com_google_protobuf/libprotobuf_lite.lo(wire_format_lite.o)
ld: 3927 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
```

**Comment by cancan101** [comment]
I can confirm that for me, Android builds against `v0.9.3.0` fail whereas I can successfully build against `v0.9.2.1`.

**Comment by trungdinhth** [comment]
I've tested with `v0.10.1` the problem persists for macOS with x86_64, even though on arm64, there is no problem.

**Comment by kuaashish** [comment]
@schmidt-sebastian,

I am able to reproduce the issue in macOS Intel Core i7, with `v0.10.2`And encountering the same error as screenshot attached below. Could you please share any possible reason of the build failure.

<img width="1717" alt="Screenshot 2023-07-19 at 2 36 09 PM" src="https://github.com/google/mediapipe/assets/98159216/0b0263f0-eaf9-426b-8ee6-4971a6db661f">

Thank you

**Comment by kuaashish** [comment]
Hi @fengyun21,

Could you please confirm if you still require assistance with this matter? If so, we would like to inform you that AAR solutions for app development are no longer under maintenance, and we anticipate that the reported issue will not be resolved.

Instead, we recommend utilizing our new Hand Landmarker Task API. This API is an enhanced version of our legacy Hand Solution. Further details can be found [here](https://developers.google.com/mediapipe/solutions/guide#legacy).

Additionally, you may refer to the corresponding Overview [documentation](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker) and implementation instructions for Android on this [page](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/android). Should you encounter any issues during implementation, please feel free to report them to us.

Thank you!!
