### ISSUE TITLE
Application crashing upon upgrading to latest mediapipe in android

### ISSUE THREAD

**Issue by Sagar1711** [google/mediapipe#4685]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Android 13

### Mobile device if the issue happens on mobile device

Samsung Galaxy S22 Ultra, and newer devices

### Programming Language and version

Kotlin

### MediaPipe version

0.20230731

### Solution

Pose

### Describe the actual behavior

```shell
While running mediapipe release 0.20230731, which has the implementation of visibility and presence parameters, the app crashes as soon as I run it. I am using mediapipe sample code from Pose android sample.

It fails with below error:

type=1400 audit(1691617574.011:420): avc:  granted  { execute } for  pid=4390 comm="install_server-" path="/data/data/com.google.mediapipe.examples.poselandmarker/code_cache/install_server-566ca8ec" dev="dm-53" ino=12403 scontext=u:r:runas_app:s0:c70,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c70,c257,c512,c768 tclass=file SEPF_SM-S908U1_12_0001 audit_filtered
type=1400 audit(1691617574.367:425): avc:  granted  { execute } for  pid=4417 comm="re-initialized>" path="/data/data/com.google.mediapipe.examples.poselandmarker/code_cache/startup_agents/566ca8ec-agent.so" dev="dm-53" ino=12407 scontext=u:r:untrusted_app:s0:c70,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c70,c257,c512,c768 tclass=file SEPF_SM-S908U1_12_0001 audit_filtered
Cmdline: com.google.mediapipe.examples.poselandmarker
pid: 4417, tid: 4505, name: pool-3-thread-1  >>> com.google.mediapipe.examples.poselandmarker <<<
      #00 pc 0000000000889550  /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk
      #01 pc 000000000088a964  /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk
      #02 pc 00000000005e9600  /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk
      #22 pc 00000000001ef19c  [anon:dalvik-classes6.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes6.dex] (com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>+4)
      #30 pc 0000000000003356  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes4.dex] (com.google.mediapipe.examples.poselandmarker.PoseLandmarkerHelper.setupPoseLandmarker+306)
      #32 pc 0000000000002e90  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes4.dex] (com.google.mediapipe.examples.poselandmarker.PoseLandmarkerHelper.<init>+60)
      #34 pc 0000000000002f2c  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes4.dex] (com.google.mediapipe.examples.poselandmarker.PoseLandmarkerHelper.<init>+128)
      #36 pc 00000000000042e0  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes3.dex] (com.google.mediapipe.examples.poselandmarker.fragment.CameraFragment.onViewCreated$lambda$3+128)
      #38 pc 00000000000033cc  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes3.dex] (com.google.mediapipe.examples.poselandmarker.fragment.CameraFragment.$r8$lambda$ic9d0Oj96cBp6BrE6b9LZP9KTw0+0)
      #40 pc 0000000000002e34  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~OhXXV8Y79XgWViRAMKGrjg==/com.google.mediapipe.examples.poselandmarker-WpPqyk97Tl-0APXoc00k4Q==/base.apk!classes3.dex] (com.google.mediapipe.examples.poselandmarker.fragment.CameraFragment$$ExternalSyntheticLambda3.run+4)
```

### Describe the expected behaviour

```shell
It should run and detect the pose
```

### Standalone code/steps you may have used to try to get what you need

```shell
Code is at https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/android/app/src/main/java/com/google/mediapipe/examples/poselandmarker

Using new mediapipe release: 
// MediaPipe Library
    implementation 'com.google.mediapipe:tasks-vision:0.20230731'
```

**Comment by akshat220** [comment]
I am also getting the same crash on Samsung Galaxy S23, Android 13 with the following dependency
`com.google.mediapipe:tasks-vision:0.20230731`

> Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x31af72430ea0f8 in tid 2812 (indwealth.debug), pid 2812 (indwealth.debug)
Cmdline: in.indwealth.debug
pid: 2812, tid: 2812, name: indwealth.debug  >>> in.indwealth.debug <<<
#00 pc 0000000000889550  /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk
#01 pc 000000000088a964  /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk
#02 pc 00000000005e9600  /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk
#22 pc 0000000000184610  [anon:dalvik-classes5.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes5.dex] (com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>+4)
#30 pc 0000000000351bc6  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.FaceDetectorHelper.setupFaceDetector+186)
#32 pc 0000000000351814  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.FaceDetectorHelper.<init>+40)
#34 pc 0000000000351850  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.FaceDetectorHelper.<init>+32)
#36 pc 0000000000353d3e  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.setUpFeVision+114)
#38 pc 0000000000354e52  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.initCamera+146)
#40 pc 0000000000354da6  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.init+122)
#42 pc 0000000000354a1c  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.handleViewStates+288)
#44 pc 0000000000354f78  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.observe$lambda-0+20)
#46 pc 0000000000354f08  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.LivelinessCheckActivity.lambda$EmZN_PlyWuI7AxS0jIQZerQa15g+0)
#48 pc 0000000000350e18  [anon:dalvik-classes14.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk!classes14.dex] (com.indwealth.common.kyc.kycliveliness.-$$Lambda$LivelinessCheckActivity$EmZN_PlyWuI7AxS0jIQZerQa15g.onChanged+8)
#50 pc 0000000000383fde  [anon:dalvik-classes.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk] (androidx.lifecycle.LiveData.considerNotify+58)
#52 pc 0000000000384050  [anon:dalvik-classes.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk] (androidx.lifecycle.LiveData.dispatchingValue+88)
#54 pc 00000000003842ba  [anon:dalvik-classes.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk] (androidx.lifecycle.LiveData.setValue+30)
#56 pc 0000000000384594  [anon:dalvik-classes.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk] (androidx.lifecycle.MutableLiveData.setValue+0)
#58 pc 00000000003837b8  [anon:dalvik-classes.dex extracted in memory from /data/app/~~o0foJLWQTr97o_cXJavMBA==/in.indwealth.debug-9VOEUwg9aeKcKiAcEqg3vQ==/base.apk] (androidx.lifecycle.LiveData$1.run+36)

**Comment by yichunk** [comment]
We can confirm the crash report on the same device, and are working on the solution to it.
Meanwhile, please consider to use older version for these devices instead.

**Comment by schmidt-sebastian** [comment]
This has been fixed by 0.15.2.

**Comment by bruno-centanaro-qubika** [comment]
> This has been fixed by 0.15.2.

Where should i use that 0.15.2? as 0.20230731 is newer?

**Comment by shreks7** [comment]
Still getting this issue in 0.20230731
`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10e1fb216e3324 in tid 2502 (pool-8-thread-1), pid 2428`

**Comment by victorchacn** [comment]
Hello.

I had the same issue with an Android S23 but managed to resolve it by using the latest version of Mediapipe (0.10.10)!
