### ISSUE TITLE
@mediapipe/tasks-vision has a problem in types exports in package.json

### ISSUE THREAD

**Issue by rohitsharma120582** [google/mediapipe#4823]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)
No

### OS Platform and Distribution
TypeScript

### Programming Language and version
TypeScript: 5.0.2

### MediaPipe version
@mediapipe/tasks-vision: 0.10.6

### Solution
Need to fix the entry for "types" under exports in package.json

### Describe the actual behavior
TypeScript: Could not find a declaration file for module `@mediapipe/tasks-vision`

```shell
"exports": {
    ...,
    "types":  "./vision_.d.ts"
}
```

### Describe the expected behaviour
`"types": "./vision.d.ts"` // should be corrected under **exports** in **package.json**. It should be without underscore (_)

```shell
"exports": {
    ...,
    "types":  "./vision.d.ts"
}
```

### Standalone code/steps you may have used to try to get what you need
```shell
import { FilesetResolverObjectDetector, ObjectDetectorResult } from "@mediapipe/tasks-vision";
```

**Comment by siva-globant** [comment]
+1

**Comment by kuaashish** [comment]
@rohitsharma120582,

Thank you for reporting this. We are looking into the issue and will update you once it has been fixed from our end.

**Comment by danish-pf** [comment]
+1

**Comment by kuaashish** [comment]
This issue has been fixed in the nightly version [here](https://www.npmjs.com/package/@mediapipe/tasks-vision/v/0.0.0-nightly-20230924?activeTab=code). Could you please build and verify whether it is working or not?

**Comment by danish-pf** [comment]
@kuaashish I'm still seeing the same error with this nightly.

**Comment by kuaashish** [comment]
@danish-pf,

Could you please share the complete error log which you are getting with nightly version. Thank you

**Comment by rohitsharma120582** [comment]
Thanks @kuaashish! I find that the issue is resolved in the beta version as below
```
npm i @mediapipe/tasks-vision@0.0.0-nightly-20230924
```

**Comment by kuaashish** [comment]
@rohitsharma120582,

Thank you for your confirmation, This will be part of the major release probably. However, We need your confirmation to move the issue status to resolved and close this if now no longer issue from your end.

**Comment by rohitsharma120582** [comment]
It's fixed.
