### ISSUE TITLE
Failed access to mp.tasks.vision.holistic

### ISSUE THREAD

**Issue by PaStMir** [google/mediapipe#5174]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows x64

### MediaPipe Tasks SDK version

0.10.10

### Task name (e.g. Image classification, Gesture recognition etc.)

mp.tasks.vision.holistic_landmarker

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

mp.tasks.vision.holistic is listed as a module, but its not callable 

### Describe the expected behaviour

Callable as module 

### Standalone code/steps you may have used to try to get what you need

```shell
Due to the new updated version, we want to add the new functions to our code, so we need to restructure it. But we can't do it as long as the module is not callable.
```

**Comment by ayushgdev** [comment]
Hello @PaStMir 
Thanks for reporting this bug. We are able to reproduce the issue and we shall fix it shortly and provide a solution in next release. Meanwhile, you can import HolisticLandmarker as 
`from mediapipe.tasks.python.vision.holistic_landmarker import HolisticLandmarker`

**Comment by ayushgdev** [comment]
Hello @PaStMir 
The error has been fixed. It would be released in stable release later. However, if you need to, you can use the nightly package for the time being since your app code is most likely not to change drastically between nightly and stable release.
Tested the following import statement with latest nightly version (mediapipe-nightly 0.10.11.post20240229)
```python
from mediapipe.tasks.python.vision import HolisticLandmarker
```

**Comment by DehTop** [comment]
> Hello @PaStMir The error has been fixed. It would be released in stable release later. However, if you need to, you can use the nightly package for the time being since your app code is most likely not to change drastically between nightly and stable release. Tested the following import statement with latest nightly version (mediapipe-nightly 0.10.11.post20240229)
> 
> ```python
> from mediapipe.tasks.python.vision import HolisticLandmarker
> ```

I tried the above and the import works, but the rest is still failing as also reported in #5181 :(

**Comment by kuaashish** [comment]
Hi @DehTop,

We are closing this issue as resolved, as the import-related matter is expected to be part in the upcoming release. For further GPU-related concerns, please follow up with #5181.

Thank you!
