### ISSUE TITLE
Error running Hello World example

### ISSUE THREAD

**Issue by Dylan5100** [google/mediapipe#732]
Hi guys. So I followed the instructions from [MediaPipe v0.5 documentation](https://mediapipe.readthedocs.io/en/latest/install.html#installing-on-debian-and-ubuntu) 
to install mediapipe on Ubuntu in VMWare. I've reinstalled the entire virtual machine, installed Bazel 3.1.0 and 2.0.0, and it still shows the same error. The installation process runs smoothly without error until the Hello World desktop example step (number 5). So here's what i did and the error showed:

`
$ bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 4d32debb2de7e3d0a96b59859d3effc9860f8d1d1dedc0eae8e74bef86295b26
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "4d32debb2de7e3d0a96b59859d3effc9860f8d1d1dedc0eae8e74bef86295b26"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/dylan/Desktop/mediapipe/WORKSPACE:33:1
INFO: Call stack for the definition of repository 'local_execution_config_python' which is a local_python_configure (rule definition at /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/py/python_configure.bzl:275:26):
 - /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:5
 - /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:5
 - /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/tensorflow/workspace.bzl:93:5
 - /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/tensorflow/workspace.bzl:77:5
 - /home/dylan/Desktop/mediapipe/WORKSPACE:337:1
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Call stack for the definition of repository 'rules_java' which is a http_archive (rule definition at /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:290:1
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: invalid registered toolchain '@local_execution_config_python//:py_toolchain': no such package '@local_execution_config_python//': Traceback (most recent call last):
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: invalid registered toolchain '@local_execution_config_python//:py_toolchain': no such package '@local_execution_config_python//': Traceback (most recent call last):
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/dylan/.cache/bazel/_bazel_dylan/5ac94a32f81d7a460dae7839df07e2ce/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Elapsed time: 13.599s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (7 packages loaded, 11 targets co\
FAILED: Build did NOT complete successfully (7 packages loaded, 11 targets co\
nfigured)
    currently loading: @bazel_tools//tools/jdk ... (2 packages)

`

**Comment by jiuqiant** [comment]
Hi, the issue is the Python binary can't be found. Please install Python.

**Comment by Dylan5100** [comment]
I will try again tomorrow. Thank you!

**Comment by Dylan5100** [comment]
@jiuqiant my problems are solved now, thank you so much for your help!

**Comment by shehramjamil** [comment]
Even after installing python and numpy , I am still getting the error
no such target '@local_execution_config_python//:py_toolchain': target 'py_toolchain' not declared in package

**Comment by SteveGremory** [comment]
yes, same

**Comment by SteveGremory** [comment]
> > @jiuqiant我的问题现在解决了，非常感谢您的帮助！
> 
> Excuse me, I also encountered a similar problem, but I have installed python3.8.10, how did you solve it?
I had to actually change the paths.
