### ISSUE TITLE
Unable to join the google group mailing list

### ISSUE THREAD

**Issue by seanpmorgan** [google/mediapipe#8]
When trying to join the google group I receive this error:

```
This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.
RELOAD
````

If possible could you adjust the group permissions? Thank you for your work this looks like an excellent project.

**Comment by mgyong** [comment]
@seanpmorgan Thanks for catching this. We corrected and you should be able to join the google group [https://groups.google.com/d/forum/mediapipe](
https://groups.google.com/d/forum/mediapipe) and post messages

**Comment by seanpmorgan** [comment]
@mgyong Thanks for the follow up. Unfortunately I'm still getting the same error.

**Comment by mgyong** [comment]
@seanpmorgan Try now again. https://groups.google.com/d/forum/mediapipe 
Should work. I tried it using my other accounts

**Comment by seanpmorgan** [comment]
Can confirm. Thank you!
